# Generated by Django 5.1.4 on 2024-12-30 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_contactus_coursecategory_course_employeeprofile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='duration_in_weeks',
            new_name='duration_in_week',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('staff', 'Staff'), ('employee', 'Employee'), ('student', 'Student'), ('teacher', 'Teacher')], db_index=True, default='student', max_length=20),
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('role', models.CharField(choices=[('Math', 'Mathematics'), ('Science', 'Science'), ('English', 'English'), ('Graphical', 'Graphical'), ('CyberSecurity', 'Cyber Security'), ('DM', 'Digital Marketing'), ('AI', 'Artifical Intelligence'), ('Frontend', 'Web Design'), ('Backend', 'Software Development')], db_index=True, max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='teacher_profiles/')),
                ('nid_number', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('nid_front_image', models.ImageField(blank=True, null=True, upload_to='nid_images/front/')),
                ('nid_back_image', models.ImageField(blank=True, null=True, upload_to='nid_images/back/')),
                ('address', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Profile',
                'verbose_name_plural': 'Teacher Profiles',
                'indexes': [models.Index(fields=['user', 'is_active'], name='project_app_user_id_7015c4_idx'), models.Index(fields=['role', 'created_at'], name='project_app_role_d5a177_idx'), models.Index(fields=['nid_number'], name='project_app_nid_num_c342b4_idx')],
                'unique_together': {('user', 'role')},
            },
        ),
    ]
