# Generated by Django 5.1.4 on 2024-12-31 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_rename_duration_in_weeks_course_duration_in_week_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='is_approved',
            new_name='is_viewed',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='is_urgent',
        ),
    ]
