# Generated by Django 5.1.4 on 2024-12-31 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_rename_is_approved_contactus_is_viewed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('role', models.CharField(choices=[('Web_Developer', 'Web Developer'), ('Software_Developer', 'Software Developer'), ('Graphic_Designer', 'Graphic Designer'), ('Digital_Marketer', 'Digital Marketer'), ('Content_Creator', 'Content Creator'), ('UI_UX_Designer', 'UI/UX Designer'), ('Video_Editor', 'Video Editor'), ('SEO_Expert', 'SEO Expert'), ('Data_Scientist', 'Data Scientist'), ('App_Developer', 'App Developer'), ('Cybersecurity_Analyst', 'Cybersecurity Analyst'), ('Penetration_Tester', 'Penetration Tester'), ('Network_Engineer', 'Network Engineer'), ('Cloud_Specialist', 'Cloud Specialist'), ('DevOps_Engineer', 'DevOps Engineer'), ('IT_Support_Specialist', 'IT Support Specialist'), ('Security_Architect', 'Security Architect'), ('Blockchain_Developer', 'Blockchain Developer'), ('Cryptocurrency_Analyst', 'Cryptocurrency Analyst'), ('Data_Analyst', 'Data Analyst'), ('AI_Researcher', 'AI Researcher'), ('Machine_Learning_Engineer', 'Machine Learning Engineer'), ('Project_Manager', 'Project Manager'), ('Business_Analyst', 'Business Analyst'), ('HR_Specialist', 'HR Specialist'), ('Quality_Assurance', 'Quality Assurance'), ('Technical_Writer', 'Technical Writer'), ('Product_Designer', 'Product Designer'), ('Game_Developer', 'Game Developer'), ('Database_Administrator', 'Database Administrator'), ('Network_Administrator', 'Network Administrator'), ('Embedded_Systems_Engineer', 'Embedded Systems Engineer'), ('Electrical_Engineer', 'Electrical Engineer'), ('Civil_Engineer', 'Civil Engineer'), ('Legal_Consultant', 'Legal Consultant'), ('Marketing_Strategist', 'Marketing Strategist'), ('Consultant', 'Consultant'), ('Sales_Expert', 'Sales Expert'), ('Financial_Analyst', 'Financial Analyst')], db_index=True, max_length=50)),
                ('profession_type', models.CharField(choices=[('Freelancer', 'Freelancer'), ('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contractor', 'Contractor'), ('Intern', 'Intern')], db_index=True, default='Freelancer', max_length=20)),
                ('education_level', models.CharField(blank=True, choices=[('HighSchool', 'High School'), ('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate'), ('PostGraduate', 'Post Graduate'), ('PhD', 'PhD'), ('Other', 'Other'), ('NotSpecified', 'Not Specified')], max_length=20, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Other', 'Other'), ('NotSpecified', 'Not Specified')], max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('PreferNotToSay', 'Prefer Not to Say'), ('NotSpecified', 'Not Specified')], max_length=20, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Freelancer Profile',
                'verbose_name_plural': 'Freelancer Profiles',
                'indexes': [models.Index(fields=['full_name'], name='project_app_full_na_477d20_idx'), models.Index(fields=['role', 'created_at'], name='project_app_role_0ae37a_idx')],
            },
        ),
    ]
