# Generated by Django 5.1.4 on 2024-12-31 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0005_freelancerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=15, null=True),
        ),
    ]
