# Generated by Django 5.1.4 on 2025-01-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0006_freelancerprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='marketer_name',
            field=models.CharField(blank=True, help_text="Marketer's full name", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='profession_type',
            field=models.CharField(choices=[('Freelancer', 'Freelancer'), ('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Student', 'Student'), ('Intern', 'Intern')], db_index=True, default='Freelancer', max_length=20),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='role',
            field=models.CharField(choices=[('abcmath', 'Abcus Math'), ('Spoken_English', 'Spoken English'), ('Kids_Science', 'Kids Science'), ('Digital_Art', 'Digital Art'), ('Digital_Design', 'Digital Design'), ('Web_Design', 'Web Design'), ('BD', 'Backend Development'), ('CS', 'Cyber Security'), ('Ielts', 'IELTS'), ('BC', 'Business Communication'), ('SK', 'Soft Skills')], db_index=True, max_length=50),
        ),
    ]
